let currentQuery = null;
let idToken = null;

// ============================================================================
// COGNITO AUTH CONFIGURATION
// Values loaded from config.js (generated by deploy-lambda.sh, gitignored)
// ============================================================================
const COGNITO_CONFIG = {
    domain: (typeof COGNITO_DOMAIN !== 'undefined') ? COGNITO_DOMAIN : '',
    appClient: (typeof COGNITO_APP_CLIENT !== 'undefined') ? COGNITO_APP_CLIENT : '',
    redirectUri: 'http://localhost:8000',
    scopes: 'openid email profile'
};

// Sanitize HTML via DOMPurify and set element content safely using DOM API
function safeSetHtml(element, html) {
    const clean = DOMPurify.sanitize(html, { RETURN_DOM_FRAGMENT: true });
    element.textContent = '';
    element.appendChild(clean);
}

// Escape HTML special characters to prevent XSS in template literals
function escapeHtml(str) {
    if (str === null || str === undefined) return '';
    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

// Show a non-blocking notification banner instead of alert()
function showNotification(message) {
    var existing = document.getElementById('notificationBanner');
    if (existing) existing.remove();
    var banner = document.createElement('div');
    banner.id = 'notificationBanner';
    banner.setAttribute('role', 'alert');
    banner.style.cssText = 'position:fixed;top:20px;left:50%;transform:translateX(-50%);background:#f59e0b;color:#000;padding:12px 24px;border-radius:8px;z-index:9999;font-weight:500;box-shadow:0 4px 12px rgba(0,0,0,0.15);';
    banner.textContent = message;
    document.body.appendChild(banner);
    setTimeout(function() { if (banner.parentNode) banner.remove(); }, 4000);
}

// Safely format a number (returns number or fallback, no escaping needed for pure numbers)
function safeNum(val, fallback) {
    if (typeof val === 'number' && isFinite(val)) return val;
    if (fallback !== undefined) return fallback;
    return 0;
}

// ============================================================================
// COGNITO AUTH FUNCTIONS
// ============================================================================

// Parse token from URL hash (Cognito implicit flow redirect)
function parseAuthTokenFromUrl() {
    var hash = window.location.hash.substring(1);
    if (!hash) return null;
    var params = {};
    hash.split('&').forEach(function(part) {
        var kv = part.split('=');
        params[decodeURIComponent(kv[0])] = decodeURIComponent(kv[1] || '');
    });
    return params.id_token || null;
}

// Decode JWT payload (no verification — API Gateway validates the token)
function decodeJwtPayload(token) {
    try {
        var payload = token.split('.')[1];
        return JSON.parse(atob(payload.replace(/-/g, '+').replace(/_/g, '/')));
    } catch (e) {
        return null;
    }
}

// Check if token is expired
function isTokenExpired(token) {
    var payload = decodeJwtPayload(token);
    if (!payload || !payload.exp) return true;
    return Date.now() >= payload.exp * 1000;
}

// Update auth UI state
function updateAuthUI() {
    var authStatus = document.getElementById('authStatus');
    var authIcon = document.getElementById('authIcon');
    var authPill = document.getElementById('authPill');
    var authDropdown = document.getElementById('authDropdown');
    var authDropdownEmail = document.getElementById('authDropdownEmail');
    if (!authStatus || !authIcon || !authPill) return;

    if (authDropdown) authDropdown.classList.remove('visible');

    if (idToken && !isTokenExpired(idToken)) {
        var payload = decodeJwtPayload(idToken);
        var email = (payload && payload.email) ? payload.email : 'Authenticated';
        var initial = email.charAt(0).toUpperCase();
        authStatus.textContent = 'Signed In';
        authIcon.innerHTML = '<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="8" r="4"/><path d="M20 21a8 8 0 1 0-16 0"/></svg>';
        authPill.classList.add('signed-in');
        if (authDropdownEmail) authDropdownEmail.textContent = email;
    } else {
        idToken = null;
        authStatus.textContent = 'Sign In';
        authIcon.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M20 21a8 8 0 1 0-16 0"/></svg>';
        authPill.classList.remove('signed-in');
    }
}

// Handle auth pill click — sign in or toggle dropdown
function handleAuth() {
    if (idToken && !isTokenExpired(idToken)) {
        var dropdown = document.getElementById('authDropdown');
        if (dropdown) dropdown.classList.toggle('visible');
    } else {
        if (!COGNITO_CONFIG.domain || !COGNITO_CONFIG.appClient) {
            showNotification('Set COGNITO_CONFIG in app.js with your stack outputs');
            return;
        }
        window.location.href = 'https://' + COGNITO_CONFIG.domain
            + '/login?client_id=' + COGNITO_CONFIG.appClient
            + '&response_type=token'
            + '&scope=' + encodeURIComponent(COGNITO_CONFIG.scopes)
            + '&redirect_uri=' + encodeURIComponent(COGNITO_CONFIG.redirectUri);
    }
}

// Handle sign out from dropdown
function handleSignOut() {
    idToken = null;
    sessionStorage.removeItem('idToken');
    updateAuthUI();
    showNotification('Signed out');
    if (COGNITO_CONFIG.domain && COGNITO_CONFIG.appClient) {
        window.location.href = 'https://' + COGNITO_CONFIG.domain
            + '/logout?client_id=' + COGNITO_CONFIG.appClient
            + '&logout_uri=' + encodeURIComponent(COGNITO_CONFIG.redirectUri);
    }
}

// Close dropdown when clicking outside
document.addEventListener('click', function(e) {
    var container = document.querySelector('.auth-container');
    var dropdown = document.getElementById('authDropdown');
    if (container && dropdown && !container.contains(e.target)) {
        dropdown.classList.remove('visible');
    }
});

// Get request headers with auth token
function getAuthHeaders() {
    var headers = { 'Content-Type': 'application/json' };
    if (idToken) {
        headers['Authorization'] = idToken;
    }
    return headers;
}

// Load saved endpoint and check for auth token on page load
window.addEventListener('DOMContentLoaded', function() {
    // Check for token in URL hash (redirect from Cognito)
    var tokenFromUrl = parseAuthTokenFromUrl();
    if (tokenFromUrl) {
        idToken = tokenFromUrl;
        sessionStorage.setItem('idToken', idToken);
        // Clean the URL hash
        history.replaceState(null, '', window.location.pathname);
    } else {
        // Try to restore from session storage
        var savedToken = sessionStorage.getItem('idToken');
        if (savedToken && !isTokenExpired(savedToken)) {
            idToken = savedToken;
        }
    }

    updateAuthUI();

    var savedEndpoint = localStorage.getItem('apiEndpoint');
    if (savedEndpoint) {
        document.getElementById('apiEndpoint').value = savedEndpoint;
        if (idToken) {
            checkHealth();
        }
    }
});

// Check API health
async function checkHealth() {
    const endpoint = document.getElementById('apiEndpoint').value.trim();
    if (!endpoint) {
        updateHealthStatus('error', 'No endpoint configured');
        return;
    }

    localStorage.setItem('apiEndpoint', endpoint);
    const healthEndpoint = endpoint.replace('/analytics', '/health');
    updateHealthStatus('checking', 'Checking...');

    try {
        const response = await fetch(healthEndpoint, {
            headers: getAuthHeaders()
        });
        const data = await response.json();

        if (data.status === 'healthy') {
            updateHealthStatus('healthy', 'Healthy - ' + safeNum(data.rows).toLocaleString() + ' rows, ' + safeNum(data.memory_gb) + 'GB');
        } else {
            updateHealthStatus('error', 'Unhealthy');
        }
    } catch (error) {
        updateHealthStatus('error', 'Connection failed');
        console.error('Health check failed:', error);
    }
}

function updateHealthStatus(status, text) {
    const indicator = document.querySelector('.status-indicator');
    const statusText = document.querySelector('.status-text');

    indicator.className = 'status-indicator';
    if (status === 'healthy') {
        indicator.classList.add('healthy');
    } else if (status === 'error') {
        indicator.classList.add('error');
    }

    statusText.textContent = text;
}

// Get system information
async function getSystemInfo() {
    const endpoint = document.getElementById('apiEndpoint').value.trim();
    if (!endpoint) {
        showNotification('Please configure API endpoint first');
        return;
    }

    const resultsContent = document.getElementById('resultsContent');
    safeSetHtml(resultsContent, '<p class="loading">⏳ Loading system info...</p>');

    try {
        const response = await fetch(endpoint, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ requestType: 'system_info' })
        });

        const data = await response.json();
        displaySystemInfo(data);
    } catch (error) {
        safeSetHtml(resultsContent, '<div class="error">❌ Error: ' + escapeHtml(error.message) + '</div>');
    }
}

function displaySystemInfo(data) {
    const resultsContent = document.getElementById('resultsContent');
    const queryMeta = document.getElementById('queryMeta');
    queryMeta.textContent = '';

    let html = '<h3>System Information</h3>';

    // Initialization Status
    html += '<div class="info-section">';
    html += '<h4>Initialization Status</h4>';
    html += '<div class="stat-grid">'
        + '<div class="stat-card ' + (data.initialization_status.data_loaded ? 'success' : 'error') + '">'
        + '<div class="label">Data Loaded</div>'
        + '<div class="value">' + (data.initialization_status.data_loaded ? '✅ Yes' : '❌ No') + '</div>'
        + '</div>'
        + '<div class="stat-card ' + (data.initialization_status.model_loaded ? 'success' : 'error') + '">'
        + '<div class="label">Model Loaded</div>'
        + '<div class="value">' + (data.initialization_status.model_loaded ? '✅ Yes' : '❌ No') + '</div>'
        + '</div>'
        + '<div class="stat-card">'
        + '<div class="label">Dataset Size</div>'
        + '<div class="value">' + safeNum(data.initialization_status.dataset_size).toLocaleString() + '</div>'
        + '</div>'
        + '<div class="stat-card">'
        + '<div class="label">Init Time</div>'
        + '<div class="value">' + (data.initialization_status.initialization_time ? safeNum(data.initialization_status.initialization_time).toFixed(2) + 's' : 'N/A') + '</div>'
        + '</div>'
        + '</div>';
    html += '</div>';

    // Dataset Info
    html += '<div class="info-section">';
    html += '<h4>Dataset Information</h4>';
    html += '<div class="stat-grid">'
        + '<div class="stat-card">'
        + '<div class="label">Rows</div>'
        + '<div class="value">' + safeNum(data.dataset_info.size).toLocaleString() + '</div>'
        + '</div>'
        + '<div class="stat-card">'
        + '<div class="label">Columns</div>'
        + '<div class="value">' + safeNum(data.dataset_info.columns.length) + '</div>'
        + '</div>'
        + '<div class="stat-card">'
        + '<div class="label">Memory Usage</div>'
        + '<div class="value">' + (data.current_memory_mb ? safeNum(data.current_memory_mb).toFixed(0) + ' MB' : 'N/A') + '</div>'
        + '</div>'
        + '</div>';
    html += '<div class="columns-list"><strong>Columns:</strong> ' + data.dataset_info.columns.map(function(c) { return escapeHtml(c); }).join(', ') + '</div>';
    html += '</div>';

    // Model Info
    html += '<div class="info-section">';
    html += '<h4>AI Model Information</h4>';
    html += '<div class="stat-grid">'
        + '<div class="stat-card">'
        + '<div class="label">Model</div>'
        + '<div class="value">' + escapeHtml(data.model_info.model_name) + '</div>'
        + '</div>'
        + '<div class="stat-card">'
        + '<div class="label">Embedding Dimension</div>'
        + '<div class="value">' + safeNum(data.model_info.embedding_dimension) + '</div>'
        + '</div>'
        + '<div class="stat-card">'
        + '<div class="label">Embeddings Cached</div>'
        + '<div class="value">' + safeNum(data.cache_info.embeddings_cached) + '</div>'
        + '</div>'
        + '</div>';
    html += '</div>';

    // Errors
    if (data.initialization_status.errors && data.initialization_status.errors.length > 0) {
        html += '<div class="info-section">';
        html += '<h4>⚠️ Errors</h4>';
        html += '<ul class="error-list">';
        data.initialization_status.errors.forEach(function(err) {
            html += '<li>' + escapeHtml(err) + '</li>';
        });
        html += '</ul>';
        html += '</div>';
    }

    safeSetHtml(resultsContent, html);
}

// Select query type
function selectQuery(queryType) {
    currentQuery = queryType;

    document.querySelectorAll('.query-btn').forEach(function(btn) { btn.classList.remove('active'); });
    event.target.closest('.query-btn').classList.add('active');

    const paramsSection = document.getElementById('paramsSection');
    const paramsInputs = document.getElementById('paramsInputs');
    paramsSection.classList.add('visible');

    // Clear previous content
    paramsInputs.textContent = '';

    // Build form elements programmatically (avoids DOMPurify stripping event handlers)
    if (queryType === 'customer_analysis') {
        var div1 = document.createElement('div');
        div1.className = 'param-input';
        var label1 = document.createElement('label');
        label1.textContent = 'User ID(s)';
        var textarea = document.createElement('textarea');
        textarea.id = 'userId';
        textarea.placeholder = 'Enter one or multiple User IDs (comma or newline separated)\ne.g., user_000001, user_000100, user_001000';
        textarea.rows = 3;
        textarea.style.width = '400px';
        textarea.value = 'user_000001, user_000100';
        var small = document.createElement('small');
        small.style.cssText = 'color: #6b7280; font-size: 12px;';
        small.textContent = 'Valid format: user_XXXXXX (6 digits with leading zeros, e.g., user_000001 to user_099999)';
        div1.appendChild(label1);
        div1.appendChild(textarea);
        div1.appendChild(small);
        paramsInputs.appendChild(div1);

        var div2 = document.createElement('div');
        div2.className = 'param-input';
        var label2 = document.createElement('label');
        label2.innerHTML = '&nbsp;';
        var btn = document.createElement('button');
        btn.className = 'execute-btn';
        btn.textContent = 'Analyze Customer(s)';
        btn.addEventListener('click', function() { executeQuery(); });
        div2.appendChild(label2);
        div2.appendChild(btn);
        paramsInputs.appendChild(div2);

    } else if (queryType === 'semantic_search') {
        var div1 = document.createElement('div');
        div1.className = 'param-input';
        var label1 = document.createElement('label');
        label1.textContent = 'Search Query';
        var input1 = document.createElement('input');
        input1.type = 'text';
        input1.id = 'searchQuery';
        input1.placeholder = 'e.g., high value customers';
        input1.style.width = '300px';
        div1.appendChild(label1);
        div1.appendChild(input1);
        paramsInputs.appendChild(div1);

        var div2 = document.createElement('div');
        div2.className = 'param-input';
        var label2 = document.createElement('label');
        label2.textContent = 'Top N Results';
        var input2 = document.createElement('input');
        input2.type = 'number';
        input2.id = 'topN';
        input2.value = '5';
        input2.min = '1';
        input2.max = '20';
        div2.appendChild(label2);
        div2.appendChild(input2);
        paramsInputs.appendChild(div2);

        var div3 = document.createElement('div');
        div3.className = 'param-input';
        var label3 = document.createElement('label');
        label3.innerHTML = '&nbsp;';
        var btn = document.createElement('button');
        btn.className = 'execute-btn';
        btn.textContent = 'Search';
        btn.addEventListener('click', function() { executeQuery(); });
        div3.appendChild(label3);
        div3.appendChild(btn);
        paramsInputs.appendChild(div3);

    } else if (queryType === 'cohort_analysis') {
        // Device select
        var div1 = document.createElement('div');
        div1.className = 'param-input';
        var label1 = document.createElement('label');
        label1.textContent = 'Device';
        var select1 = document.createElement('select');
        select1.id = 'filterDevice';
        ['', 'mobile', 'desktop', 'tablet'].forEach(function(val) {
            var opt = document.createElement('option');
            opt.value = val;
            opt.textContent = val === '' ? 'All' : val.charAt(0).toUpperCase() + val.slice(1);
            select1.appendChild(opt);
        });
        div1.appendChild(label1);
        div1.appendChild(select1);
        paramsInputs.appendChild(div1);

        // Country input
        var div2 = document.createElement('div');
        div2.className = 'param-input';
        var label2 = document.createElement('label');
        label2.textContent = 'Country';
        var input1 = document.createElement('input');
        input1.type = 'text';
        input1.id = 'filterCountry';
        input1.placeholder = 'e.g., USA';
        div2.appendChild(label2);
        div2.appendChild(input1);
        paramsInputs.appendChild(div2);

        // Age group select
        var div3 = document.createElement('div');
        div3.className = 'param-input';
        var label3 = document.createElement('label');
        label3.textContent = 'Age Group';
        var select2 = document.createElement('select');
        select2.id = 'filterAgeGroup';
        ['', '18-24', '25-34', '35-44', '45-54', '55+'].forEach(function(val) {
            var opt = document.createElement('option');
            opt.value = val;
            opt.textContent = val === '' ? 'All' : val;
            select2.appendChild(opt);
        });
        div3.appendChild(label3);
        div3.appendChild(select2);
        paramsInputs.appendChild(div3);

        // Execute button
        var div4 = document.createElement('div');
        div4.className = 'param-input';
        var label4 = document.createElement('label');
        label4.innerHTML = '&nbsp;';
        var btn = document.createElement('button');
        btn.className = 'execute-btn';
        btn.textContent = 'Analyze Cohort';
        btn.addEventListener('click', function() { executeQuery(); });
        div4.appendChild(label4);
        div4.appendChild(btn);
        paramsInputs.appendChild(div4);
    }
}

// Execute query
async function executeQuery() {
    const endpoint = document.getElementById('apiEndpoint').value.trim();
    if (!endpoint) {
        showNotification('Please configure API endpoint first');
        return;
    }

    if (currentQuery === 'customer_analysis') {
        const userIdInput = document.getElementById('userId').value.trim();
        if (!userIdInput) {
            showNotification('Please enter at least one User ID');
            return;
        }

        const userIds = userIdInput
            .split(/[,\n]+/)
            .map(function(id) { return id.trim(); })
            .filter(function(id) { return id.length > 0; });

        if (userIds.length === 0) {
            showNotification('Please enter at least one valid User ID');
            return;
        }

        await executeMultipleCustomerAnalysis(endpoint, userIds);
        return;
    }

    var requestBody = { requestType: currentQuery };

    if (currentQuery === 'semantic_search') {
        var query = document.getElementById('searchQuery').value.trim();
        if (!query) {
            showNotification('Please enter a search query');
            return;
        }
        requestBody.query = query;
        requestBody.topN = parseInt(document.getElementById('topN').value) || 5;
    } else if (currentQuery === 'cohort_analysis') {
        var filters = {};
        var device = document.getElementById('filterDevice').value;
        var country = document.getElementById('filterCountry').value.trim();
        var ageGroup = document.getElementById('filterAgeGroup').value;

        if (device) filters.device = device;
        if (country) filters.country = country;
        if (ageGroup) filters.age_group = ageGroup;

        requestBody.filters = filters;
    }

    var resultsContent = document.getElementById('resultsContent');
    safeSetHtml(resultsContent, '<p class="loading">⏳ Processing request...</p>');

    try {
        var startTime = Date.now();
        var response = await fetch(endpoint, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(requestBody)
        });

        if (!response.ok) {
            throw new Error('HTTP ' + response.status + ': ' + response.statusText);
        }

        var data = await response.json();
        var queryTime = Date.now() - startTime;

        displayResults(data, queryTime);
    } catch (error) {
        safeSetHtml(resultsContent, '<div class="error">❌ Error: ' + escapeHtml(error.message) + '</div>');
        console.error('Query failed:', error);
    }
}

// Execute customer analysis for multiple users (separate Lambda events)
async function executeMultipleCustomerAnalysis(endpoint, userIds) {
    var resultsContent = document.getElementById('resultsContent');
    var queryMeta = document.getElementById('queryMeta');

    safeSetHtml(resultsContent,
        '<div class="multi-user-progress">'
        + '<h3>🔄 Analyzing ' + safeNum(userIds.length) + ' Customer(s)</h3>'
        + '<p class="progress-info">Sending separate request for each user...</p>'
        + '<div class="progress-text" id="progressText">0 / ' + safeNum(userIds.length) + ' completed</div>'
        + '</div>'
    );

    var startTime = Date.now();
    var results = [];
    var errors = [];
    var completed = 0;

    async function fetchUserAnalysis(userId) {
        try {
            var response = await fetch(endpoint, {
                method: 'POST',
                headers: getAuthHeaders(),
                body: JSON.stringify({
                    requestType: 'customer_analysis',
                    userId: userId
                })
            });

            if (!response.ok) {
                throw new Error('HTTP ' + response.status);
            }

            var responseData = await response.json();

            var data;
            if (responseData.body) {
                data = typeof responseData.body === 'string'
                    ? JSON.parse(responseData.body)
                    : responseData.body;
            } else {
                data = responseData;
            }

            console.log('Parsed data for', userId, ':', data);

            if (data.error) {
                return { success: false, userId: userId, error: data.error };
            }

            return { success: true, userId: userId, data: data };
        } catch (error) {
            console.error('Error fetching user', userId, ':', error);
            return { success: false, userId: userId, error: error.message };
        }
    }

    var promises = userIds.map(function(userId) {
        return fetchUserAnalysis(userId).then(function(result) {
            completed++;

            var progressText = document.getElementById('progressText');
            if (progressText) {
                progressText.textContent = completed + ' / ' + userIds.length + ' completed';
            }

            if (result.success) {
                results.push(result);
            } else {
                errors.push(result);
            }

            return result;
        });
    });

    await Promise.all(promises);

    var totalTime = Date.now() - startTime;
    var avgTime = totalTime / userIds.length;

    console.log('Results:', results);
    console.log('Errors:', errors);
    console.log('Total time:', totalTime);

    safeSetHtml(queryMeta,
        'Total Time: <strong>' + safeNum(totalTime) + 'ms</strong> | '
        + 'Avg per User: <strong>' + safeNum(avgTime).toFixed(0) + 'ms</strong> | '
        + 'Requests Sent: <strong>' + safeNum(userIds.length) + '</strong> | '
        + 'Success: <strong>' + safeNum(results.length) + '</strong> | '
        + 'Errors: <strong>' + safeNum(errors.length) + '</strong>'
    );

    displayMultipleCustomerResults(results, errors, totalTime);
}

function displayMultipleCustomerResults(results, errors, totalTime) {
    var resultsContent = document.getElementById('resultsContent');

    console.log('displayMultipleCustomerResults called with:', { results: results, errors: errors, totalTime: totalTime });

    try {
        var html = '<h3>📊 Customer Analysis Results</h3>';
        html += '<div class="multi-user-summary">'
            + '<div class="summary-stat">✅ Successful: ' + safeNum(results.length) + '</div>'
            + '<div class="summary-stat">❌ Failed: ' + safeNum(errors.length) + '</div>'
            + '<div class="summary-stat">⏱️ Total Time: ' + safeNum(totalTime) + 'ms</div>'
            + '<div class="summary-stat">⚡ Avg Time: ' + (safeNum(totalTime) / (results.length + errors.length || 1)).toFixed(0) + 'ms</div>'
            + '</div>';

        if (errors.length > 0) {
            html += '<div class="error-section">';
            html += '<h4>⚠️ Errors</h4>';
            errors.forEach(function(err) {
                html += '<div class="error-item">User ' + escapeHtml(err.userId) + ': ' + escapeHtml(err.error) + '</div>';
            });
            html += '</div>';
        }

        if (results.length > 0) {
            html += '<div class="results-grid">';

            results.forEach(function(result) {
                console.log('Processing result:', result);
                var data = result.data;

                console.log('Data structure check:', {
                    hasData: !!data,
                    hasUserId: !!(data && data.user_id),
                    hasMetrics: !!(data && data.metrics),
                    dataKeys: data ? Object.keys(data) : [],
                    fullData: data
                });

                if (!data) {
                    console.error('No data object for user', result.userId);
                    html += '<div class="customer-card"><div class="error">No data returned for user ' + escapeHtml(result.userId) + '</div></div>';
                    return;
                }

                if (!data.user_id) {
                    console.error('Missing user_id in data:', data);
                    html += '<div class="customer-card"><div class="error">Missing user_id for ' + escapeHtml(result.userId) + '. Data keys: ' + Object.keys(data).map(function(k) { return escapeHtml(k); }).join(', ') + '</div></div>';
                    return;
                }

                if (!data.metrics) {
                    console.error('Missing metrics in data:', data);
                    html += '<div class="customer-card"><div class="error">Missing metrics for ' + escapeHtml(data.user_id) + '. Data keys: ' + Object.keys(data).map(function(k) { return escapeHtml(k); }).join(', ') + '</div></div>';
                    return;
                }

                html += '<div class="customer-card">'
                    + '<div class="card-header">'
                    + '<h4>👤 ' + escapeHtml(data.user_id) + '</h4>'
                    + '<span class="segment-badge">' + escapeHtml(data.segment || 'Unknown') + '</span>'
                    + '</div>'
                    + '<div class="card-metrics">'
                    + '<div class="metric"><span class="metric-label">Sessions</span><span class="metric-value">' + safeNum(data.metrics.total_sessions) + '</span></div>'
                    + '<div class="metric"><span class="metric-label">Purchases</span><span class="metric-value">' + safeNum(data.metrics.total_purchases) + '</span></div>'
                    + '<div class="metric"><span class="metric-label">Conversion</span><span class="metric-value">' + (safeNum(data.metrics.conversion_rate) * 100).toFixed(1) + '%</span></div>'
                    + '<div class="metric"><span class="metric-label">Total Spend</span><span class="metric-value">' + safeNum(data.metrics.total_spend).toFixed(2) + '</span></div>'
                    + '<div class="metric"><span class="metric-label">Engagement</span><span class="metric-value">' + safeNum(data.metrics.engagement_score).toFixed(1) + '/10</span></div>'
                    + '<div class="metric"><span class="metric-label">Device</span><span class="metric-value">' + escapeHtml(data.device_preference || 'Unknown') + '</span></div>'
                    + '</div>'
                    + '</div>';
            });

            html += '</div>';
        } else if (errors.length === 0) {
            html += '<p class="no-results">No results to display</p>';
        }

        safeSetHtml(resultsContent, html);
        console.log('Results displayed successfully');
    } catch (error) {
        console.error('Error displaying results:', error);
        safeSetHtml(resultsContent, '<div class="error">❌ Error displaying results: ' + escapeHtml(error.message) + '</div>');
    }
}

// Display results
function displayResults(data, queryTime) {
    var resultsContent = document.getElementById('resultsContent');
    var queryMeta = document.getElementById('queryMeta');

    safeSetHtml(queryMeta, 'Query Time: <strong>' + safeNum(queryTime) + 'ms</strong>');

    var html = '';

    if (currentQuery === 'customer_analysis') {
        html = renderCustomerAnalysis(data);
    } else if (currentQuery === 'semantic_search') {
        html = renderSemanticSearch(data);
    } else if (currentQuery === 'cohort_analysis') {
        html = renderCohortAnalysis(data);
    } else {
        html = '<pre>' + escapeHtml(JSON.stringify(data, null, 2)) + '</pre>';
    }

    safeSetHtml(resultsContent, html);
}

function renderCustomerAnalysis(data) {
    if (data.error) {
        return '<div class="error">❌ ' + escapeHtml(data.error) + '</div>';
    }

    var html = '<h3>Customer Analysis: ' + escapeHtml(data.user_id) + '</h3>';

    html += '<div class="stat-grid">'
        + '<div class="stat-card"><div class="label">Total Sessions</div><div class="value">' + safeNum(data.metrics.total_sessions) + '</div></div>'
        + '<div class="stat-card"><div class="label">Avg Session Duration</div><div class="value">' + safeNum(data.metrics.avg_session_duration).toFixed(0) + 's</div></div>'
        + '<div class="stat-card"><div class="label">Total Purchases</div><div class="value">' + safeNum(data.metrics.total_purchases) + '</div></div>'
        + '<div class="stat-card"><div class="label">Conversion Rate</div><div class="value">' + (safeNum(data.metrics.conversion_rate) * 100).toFixed(1) + '%</div></div>'
        + '<div class="stat-card"><div class="label">Total Spend</div><div class="value">' + safeNum(data.metrics.total_spend).toFixed(2) + '</div></div>'
        + '<div class="stat-card"><div class="label">Engagement Score</div><div class="value">' + safeNum(data.metrics.engagement_score).toFixed(1) + '/10</div></div>'
        + '</div>';

    html += '<div class="info-section">';
    html += '<div class="segment-badge">' + escapeHtml(data.segment) + '</div>';
    html += '<div class="device-info">Preferred Device: <strong>' + escapeHtml(data.device_preference) + '</strong></div>';
    html += '</div>';

    if (data.recent_activity && data.recent_activity.length > 0) {
        html += '<h4>Recent Activity</h4>';
        html += '<table class="data-table">';
        html += '<thead><tr><th>Timestamp</th><th>Pages</th><th>Products</th><th>Purchased</th><th>Value</th></tr></thead>';
        html += '<tbody>';
        data.recent_activity.forEach(function(activity) {
            html += '<tr>'
                + '<td>' + escapeHtml(new Date(activity.timestamp).toLocaleString()) + '</td>'
                + '<td>' + safeNum(activity.pages_visited) + '</td>'
                + '<td>' + safeNum(activity.products_viewed) + '</td>'
                + '<td>' + (activity.purchased ? '✅' : '❌') + '</td>'
                + '<td>' + safeNum(activity.purchase_value).toFixed(2) + '</td>'
                + '</tr>';
        });
        html += '</tbody></table>';
    }

    return html;
}

function renderSemanticSearch(data) {
    if (data.error) {
        return '<div class="error">❌ ' + escapeHtml(data.error) + '</div>';
    }

    var html = '<h3>🔍 Semantic Search Results</h3>';
    html += '<p class="search-info">Query: <strong>"' + escapeHtml(data.query) + '"</strong> | Searched: ' + safeNum(data.total_users_searched).toLocaleString() + ' users</p>';

    if (data.results && data.results.length > 0) {
        data.results.forEach(function(result, index) {
            html += '<div class="search-result">'
                + '<div class="result-header">'
                + '<span class="result-rank">#' + (index + 1) + '</span>'
                + '<span class="result-user">User: ' + escapeHtml(result.user_id) + '</span>'
                + '<span class="result-similarity">Similarity: ' + (safeNum(result.similarity) * 100).toFixed(1) + '%</span>'
                + '</div>'
                + '<div class="result-description">' + escapeHtml(result.description) + '</div>'
                + '<div class="result-metrics">'
                + '<span>Sessions: ' + safeNum(result.metrics.total_sessions) + '</span>'
                + '<span>Conversion: ' + (safeNum(result.metrics.conversion_rate) * 100).toFixed(1) + '%</span>'
                + '<span>Spend: ' + safeNum(result.metrics.total_spend).toFixed(2) + '</span>'
                + '<span>Engagement: ' + safeNum(result.metrics.engagement_score).toFixed(1) + '/10</span>'
                + '</div>'
                + '</div>';
        });
    } else {
        html += '<p class="no-results">No results found</p>';
    }

    return html;
}

function renderCohortAnalysis(data) {
    if (data.error) {
        return '<div class="error">❌ ' + escapeHtml(data.error) + '</div>';
    }

    var html = '<h3>Cohort Analysis</h3>';

    if (data.filters_applied && Object.keys(data.filters_applied).length > 0) {
        html += '<div class="filters-applied">';
        html += '<strong>Filters:</strong> ';
        html += Object.entries(data.filters_applied).map(function(entry) { return escapeHtml(entry[0]) + '=' + escapeHtml(entry[1]); }).join(', ');
        html += '</div>';
    }

    var metrics = data.cohort_metrics;
    html += '<div class="stat-grid">'
        + '<div class="stat-card"><div class="label">Cohort Size</div><div class="value">' + safeNum(metrics.cohort_size).toLocaleString() + '</div></div>'
        + '<div class="stat-card"><div class="label">Total Sessions</div><div class="value">' + safeNum(metrics.total_sessions).toLocaleString() + '</div></div>'
        + '<div class="stat-card"><div class="label">Avg Sessions/User</div><div class="value">' + safeNum(metrics.avg_sessions_per_user).toFixed(1) + '</div></div>'
        + '<div class="stat-card"><div class="label">Total Purchases</div><div class="value">' + safeNum(metrics.total_purchases).toLocaleString() + '</div></div>'
        + '<div class="stat-card"><div class="label">Conversion Rate</div><div class="value">' + (safeNum(metrics.conversion_rate) * 100).toFixed(1) + '%</div></div>'
        + '<div class="stat-card"><div class="label">Total Revenue</div><div class="value">' + safeNum(metrics.total_revenue).toFixed(2) + '</div></div>'
        + '<div class="stat-card"><div class="label">Avg Order Value</div><div class="value">' + safeNum(metrics.avg_order_value).toFixed(2) + '</div></div>'
        + '</div>';

    if (data.distributions) {
        html += '<div class="distributions">';

        if (data.distributions.device) {
            html += '<div class="distribution-section">';
            html += '<h4>Device Distribution</h4>';
            html += renderDistribution(data.distributions.device);
            html += '</div>';
        }

        if (data.distributions.age_group) {
            html += '<div class="distribution-section">';
            html += '<h4>Age Group Distribution</h4>';
            html += renderDistribution(data.distributions.age_group);
            html += '</div>';
        }

        if (data.distributions.country) {
            html += '<div class="distribution-section">';
            html += '<h4>Top Countries</h4>';
            var topCountries = Object.entries(data.distributions.country)
                .sort(function(a, b) { return b[1] - a[1]; })
                .slice(0, 10)
                .reduce(function(obj, entry) { obj[entry[0]] = entry[1]; return obj; }, {});
            html += renderDistribution(topCountries);
            html += '</div>';
        }

        html += '</div>';
    }

    return html;
}

function renderDistribution(data) {
    var entries = Object.entries(data).sort(function(a, b) { return b[1] - a[1]; });
    var maxValue = Math.max.apply(null, entries.map(function(entry) { return entry[1]; }));

    var html = '<div class="bar-chart">';
    entries.forEach(function(entry) {
        var label = entry[0];
        var value = entry[1];
        var percentage = (safeNum(value) / maxValue) * 100;
        html += '<div class="bar-item">'
            + '<div class="bar-label">' + escapeHtml(label) + '</div>'
            + '<div class="bar-visual" style="width: ' + percentage + '%">'
            + '<span class="bar-value">' + (safeNum(value) * 100).toFixed(1) + '%</span>'
            + '</div>'
            + '</div>';
    });
    html += '</div>';
    return html;
}
